### ISSUE TITLE
Consigli

### ISSUE THREAD

**Issue by Demaz93** [Shevraar/jovabot#1]
-Aggiunta runtime di frasi e condizioni (ex. /jova addfrase "ciao mondo"
-Aggiunta comando "Canta una canzone" ritorno di un file audio con qualche secondo di canzone
-Aggiunta comando "Facciamo un felfie" ritorno di immagine (felfie)

**Comment by Shevraar** [comment]
Le prime due feature richieste sono state aggiunte, l'ultima la lasciamo perdere.
