### ISSUE TITLE
JOVA si è rotto

### ISSUE THREAD

**Issue by cecetarrik** [Shevraar/jovabot#21]
non ci risponde più! Ormai ero assuefatto dalle sue splendide risposte, ma da un oretta non risponde più

**Comment by accodev** [comment]
Ciao! Purtroppo e' colpa dell'hosting che sto usando (cloudatcost.com), fa un po schifo e ogni tanto si rompano i server...
Ora sto riavviando la macchina nella speranza che tutto si riprenda, altrimenti gli daro' un occhio il prima possibile.

**Comment by accodev** [comment]
Ora è up.

**Comment by cecetarrik** [comment]
Top!
