### ISSUE TITLE
Jova non risponde :'(

### ISSUE THREAD

**Issue by Francesky** [Shevraar/jovabot#22]
Niente, Jova non risponde più e nemmeno dà informazioni.

**Comment by accodev** [comment]
Ciao, purtroppo l'hosting dove era situato Jova ha cancellato tutto. Ho un backup che risale a qualche mese fa, ma per ripristinare il funzionamento dovro' modificare un po' il codice. Se conosci qualcuno che fornisce hosting gratuito e sarebbe disponibile ad ospitare Jova, te ne sarei grato

**Comment by accodev** [comment]
Jovabot è di nuovo up dopo un paio di anni sabbatici.
